### ISSUE TITLE
can' connect to a local network name

### ISSUE THREAD

**Issue by jkumeboshi** [vauvenal5/yaga#34]
If I use a simple local name (such as HTTPS://nextcloudhost/) in the address instead of a full qualified doman name the application does not connect to the nextcloud server.
The application doesn't even attempt to establish a connection to the server.

**Comment by vauvenal5** [comment]
Hi. Thanks for reporting the issue. I will have some time in the next days and will have a look into this issue.

**Comment by vauvenal5** [comment]
Yes, the current URL validation requires a valid URL. I will fix that in the near future.

**Comment by igor-cali** [comment]
I experience the same issue, after installing today from F-Droid.

**Comment by dabru1984** [comment]
Using the IP address (e.g. HTTPS://192.xxx.x.xxx) the sign in page doesn't load. I guess it's the same issue.

**Comment by vauvenal5** [comment]
I will add an advanced mode, where you will be able to specify the target server in a more detailed way.

**Comment by vauvenal5** [comment]
@dabru1984 if you can proceed to the webview then it might be something else.

**Comment by dabru1984** [comment]
Thank you! OK for the advanced mode. For the load page, it doesn't load at all, i am using microg, the app is GSF dependent? Maybe I can load the page externally somehow?

**Comment by vauvenal5** [comment]
No the app should not be GSF dependent. I will be pushing today a new version with an option to disable URL validation, this should allow connection to local network names.

@dabru1984 regarding the IP issue can you retry with port specified?

Edit: However, in any case you need to have a valid SSL certificate or you have to import your self signed cert into your Android trust store, see #40.

**Comment by dabru1984** [comment]
Hello @vauvenal5 thank you for the follow up, i have tried and failed because i have a self-signed cert, so I fall into #40 issue. I'll try to follow up and add the certificate in order to proceed. Thanks

**Comment by vauvenal5** [comment]
- [ ] add documentation for `disable URL validation` feature

**Comment by dabru1984** [comment]
Thank you for the help so far but I think I would not use a certificate considering that I need to do it only to use the app... I'll look forward for other possibilities to use it without the certificate...

**Comment by vauvenal5** [comment]
I will have to try how it behaves with the browser enabled login flow, feel free to reopen #40.

Just in general, have you considered using `Let's Encrypt` certs?

**Comment by vauvenal5** [comment]
@jkumeboshi / @igor-cali can one of you confirm that connecting to a hostname is now possible with the new option to disable URL validation? So I can close this issue.

**Comment by igor-cali** [comment]
> @jkumeboshi / @igor-cali can one of you confirm that connecting to a hostname is now possible with the new option to disable URL validation? So I can close this issue.

@vauvenal5 I still cannot get to the login, even disabling the URL validation and installing my self-signed certificate on the mobile as discussed in #40.

**Comment by jkumeboshi** [comment]
Me too, I cannot connect at all.
I use a custom CA to issue certificates, and I've installed the CA cert in android system store.
It works with official nextcloud app and with Chrome as you can see from image.
I cannot even see any connect try in the nginx logs.

![IMG_20210112_220136](https://user-images.githubusercontent.com/25344258/104374522-47654400-5522-11eb-9d3f-2f801fbb2d90.jpg)

**Comment by vauvenal5** [comment]
Can you provide logcat logs?

@jkumeboshi and you are only entering `odroidn2` in the URL field?

**Comment by jkumeboshi** [comment]
@vauvenal5 sorry, but I'm not sure how to do.
I enter https://odroidn2 in the field after disabling check

Maybe logs are not enabled in the release builds from web store?
I can get only following logs after I start the web view:
```
2021-01-15 15:26:30.661 1621-1744/? D/Boost: hostingType=, hostingName={com.github.vauvenal5.yaga/org.chromium.content.app.SandboxedProcessService0:2}, callerPackage=com.github.vauvenal5.yaga, isSystem=false, isBoostNeeded=false.
2021-01-15 15:26:30.662 669-1472/? D/OemNetd: setPidForPackage: packageName=com.github.vauvenal5.yaga, pid=7190, pid=99841
2021-01-15 15:26:30.662 1621-1744/? I/ActivityManager: Start proc 7190:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:2/u0i841 for  {com.github.vauvenal5.yaga/org.chromium.content.app.SandboxedProcessService0:2} caller=com.github.vauvenal5.yaga

```

**Comment by vauvenal5** [comment]
Hi everyone! Can you confirm that your issue still exists in `v0.18.2` there I fixed another login related bug.

**Comment by igor-cali** [comment]
> Hi everyone! Can you confirm that your issue still exists in `v0.18.2` there I fixed another login related bug.

@vauvenal5 the issue still exists for me with `v0.18.2`.

**Comment by vauvenal5** [comment]
Okay! I will work on implementing the login flow v2, which is based on the system browser instead of an internal web view. This way it should fix this problem since you can reach your Nextcloud from your browsers. However, this might take a while since there will be some changes necessary in the upstream Nextcloud Dart library. See https://github.com/Viktoriaschule/dart-nextcloud/issues/20

**Comment by vauvenal5** [comment]
I just released `v0.19.0`. It supports the browser based login flow as well.

**Comment by igor-cali** [comment]
> I just released `v0.19.0`. It supports the browser based login flow as well.

Nothing happens when I tap on the `open in browser` icon.

**Comment by vauvenal5** [comment]
You do the following steps, right?

- disable validation
- enter `https://yourhostname`
- hit `open in browser`

**Comment by igor-cali** [comment]
> You do the following steps, right?
> 
>     * disable validation
> 
>     * enter `https://yourhostname`
> 
>     * hit `open in browser`

I do:
* disable validation
* enter `https://<server_ip>/<nextcloud_server_path` (my server address is something like `https://xx.xx.xx.xx/ncfolder`)
* hit `open in browser`

**Comment by vauvenal5** [comment]
Can you retrieve the logcat output?

**Comment by jkumeboshi** [comment]
Same results for me, now I get no result if I press the "continue" button to start webview and "browser" button.
Il logcat I can see following when I press both buttons

```
2021-01-19 23:00:35.798 6871-13149/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
    	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
```

well, the problem looks like to be that the dart HTTP client doesn't uses the system CA store, probably it uses an internal CA store, such as a .PEM file containing major CA certificates.

Ok, I did try to build the source and I've disabled CA cert verification adding following code in main:

```
import 'dart:io';

class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}

void main() {
  setupServiceLocator();
  HttpOverrides.global = new MyHttpOverrides();
  runApp(MyApp());
}
```

I can successfully login in nextcloud and grant access, but later I get following error:
```
I/flutter: [38;5;196m[E] ForegroundWorker - Error in forground worker: HandshakeException: Handshake error in client (OS Error: 
    	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
```
 
if I add HttpOverrides in ForegroundWorker and NextCloudService too, it works.

so definitely it's a CA validation problem.

**Comment by vauvenal5** [comment]
Hey! Thanks for the research! I will have to look up if it is possible to make Dart use the System CA store. If this is not possible I will have to think about what the proper approach might be in this case. Adding the ability to disable CA verification in general seems too dangerous. :thinking:

**Comment by vauvenal5** [comment]
Strictly speaking this is now equal to #40.

**Comment by jkumeboshi** [comment]
Yes, I agree, but I in my case the certificate is not self signed, but signed by a custom CA that is imported in the Android CA store (and of course is seen by Nextclout app and by Chrome).
Removing the webview didn't solve the problem since the Nextcloud dart client has to connect to the same HTTPS server, after login, and encounters same CA validation problem.
If you disable the CA validation you create a security breach.
I can't help very much since I don't know very well Flutter/Dart running environment. It's possible to start the step-by-step debug of this project in some way? If I start debug, I can step-debug only the Kotlin stub and nothing more.

**Comment by vauvenal5** [comment]
First things first, your are right, in truth we have two issues here:
- dealing with self signed certificates without CA
- dealing with self signed certificates with CA

One way to deal with both cases is to allow disabling verification for a specific host. This opens of course to some degree a security issue. A second way is to figure out how to make Flutter respect the system CAs. And the third option is to allow adding the CA to the Flutter trust store itself.

I have to do some research about all three of those options before I can say which way is the best to go. I believe the first option is the easiest to implement and would solve both cases. However, it brings a certain security risk of course.

About debugging line by line you will need to set up a Flutter environment to do that.

PS: I can not stress it enough that with [Let's encrypt](https://letsencrypt.org/) there is now a days an easy to use solution to this matter. It also supports cases where your server is not publicly reachable.

**Comment by vauvenal5** [comment]
Does by chance any one of you have a ready to go Dockerfile where I just have to add a self signed certificate for this case?

**Comment by vauvenal5** [comment]
Short update. I have reopened #40 and I am currently working on a fix that will allow for accepting self signed certs. 

However, making Dart use the System CAs seems to be quiet some work. Alternatively, if you are not satisfied with just the ability to accept a self signed cert I will consider adding support for importing additional CAs into Yaga directly which seems to be less work then accessing system CAs.

**Comment by vauvenal5** [comment]
Self-signed certs are supported in `v0.22.0`. Please note that Yaga will only perform finger print comparison and a check if the subject matches the host.

**Comment by Pato05** [comment]
Hi! It seems like I'm having a similar (if not same) problem. For me when I click on Open in Browser it shows if I want to trust the certificate, so I press trust, but nothing happens, the popup itself doesn't even close.

I am using version `v0.22.3`

**Comment by vauvenal5** [comment]
But in general you can connect by **https** to your local Nextcloud?

**Comment by Pato05** [comment]
> 
> 
> But in general you can connect by **https** to your local Nextcloud?

Yes, I have installed my personal CA, and chrome mobile doesn't mind it (shows the normal https lock). I also have a Pi-Hole installation but seems like it is completely ignoring the Pi-Hole DNS.

**Comment by vauvenal5** [comment]
Are you using the `Open in Browser`-login flow?

**Comment by Pato05** [comment]
> 
> 
> Are you using the `Open in Browser`-login flow?

I click the button, but only a little "Trust Certificate" popup appears, no browser is opened.

**Comment by vauvenal5** [comment]
Would you be able to provide me with logcat logs?

**Comment by Pato05** [comment]
Yessir!
Edit vauvenal5: Downloaded and removed to avoid leaking of data.

**Comment by vauvenal5** [comment]
@Pato05 is your trust dialog behavior the same as descibed in #101?

Edit: Also I had a look on your logs and there is indeed a CA error in there: 
`flutter : 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate`

**Comment by Pato05** [comment]
> @Pato05 is your trust dialog behavior the same as descibed in #101?
> 
> Edit: Also I had a look on your logs and there is indeed a CA error in there:
> `flutter : CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate`

Yes, but since I installed my CA, I don't have to click any "Proceed Anyway" button, here is a screenshot
![Screenshot_20210314-101648_Chrome~2](https://user-images.githubusercontent.com/20874747/111063403-8d9d3c00-84ae-11eb-9187-c2a5e0e8ff49.png)

**Comment by ruben-tura** [comment]
I still don't know how to make this work unfortunately.

**Comment by vauvenal5** [comment]
Flutter does not respect the system CAs. So for Flutter this is still a untrusted certificate. However, what I can not get my head around is why the Trust-Dialog is not working. I will improve logging around the cert dialog and push a new version. If @Pato05 could then send me a new logcat we might see something more.

**Comment by Pato05** [comment]
> Flutter does not respect the system CAs. So for Flutter this is still a untrusted certificate. However, what I can not get my head around is why the Trust-Dialog is not working. I will improve logging around the cert dialog and push a new version. If @Pato05 could then send me a new logcat we might see something more.

Sure thing, do I need to download another version? Because in the logcat I sent earlier, I had already clicked trust several times

**Comment by vauvenal5** [comment]
I just published `v0.22.4` once you get the update please try again an record the logs. Best send them to me by email.

**Comment by Pato05** [comment]
> 
> 
> I just published `v0.22.4` once you get the update please try again an record the logs. Best send them to me by email.

Sure, I will look into it later.

**Comment by ruben-tura** [comment]
> I just published `v0.22.4` once you get the update please try again an record the logs. Best send them to me by email.

Tried it.
Doesn't show the popup anymore, but it still doesn't open the browser, it just doesn't do anything.

EDIT:
Ok my mistake, it still shows the popup, but same behaviour as before. Nothing happens and the popup stays back on.

**Comment by vauvenal5** [comment]
@ruben-tura yes, this is expected since I only increased the log output to be able to find the actual issue.

**Comment by ruben-tura** [comment]
> @ruben-tura yes, this is expected since I only increased the log output to be able to find the actual issue.

Oh ok, sorry!

**Comment by Pato05** [comment]
@vauvenal5 Here is the interested logcat part 
```
03-19 21:33:00.141 21593  6613 I flutter : [W] SelfSignedCertHandler - Fingerprint Cert: [fingerprint]
03-19 21:33:00.141 21593  6613 I flutter : [W] SelfSignedCertHandler - Saved Fingerprint: [fingerprint]
03-19 21:33:00.141 21593  6613 I flutter : [W] SelfSignedCertHandler - Host: 192.168.1.2
03-19 21:33:00.141 21593  6613 I flutter : [W] SelfSignedCertHandler - Cert-Subject: *******************REDACTED*******************
03-19 21:33:00.142 21593  6613 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
03-19 21:33:00.142 21593  6613 E flutter : 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
03-19 21:33:00.142 21593  6613 E flutter : 
```

**Comment by vauvenal5** [comment]
@Pato05 can you confirm one more thing for me please, does your `Cert-Subject` end with your `Host`-IP?

**Comment by vauvenal5** [comment]
Just published `v0.22.8`. This should hopefully fix the issue.

**Comment by ruben-tura** [comment]
> Just published `v0.22.8`. This should hopefully fix the issue.

It works like a charm! Thank you so much!

**Comment by igor-cali** [comment]
Still does not work for me w/ `v0.28.8`.
Disabling the security I get a permanent blank page.
If I press `Open in browser` (my browser is Fennec) I can grant access, but Yaga is still on the login page.

**Comment by Pato05** [comment]
> Just published `v0.22.8`. This should hopefully fix the issue.

it does work, thanks!

**Comment by vauvenal5** [comment]
@igor-cali I just published `v0.23.1` with improved handling for self-signed certs and completely reworked logging. You can now send logs from within the global settings. Please try again and if does not work send me the logs.

**Comment by igor-cali** [comment]
`v0.23.1` worked for me.

**Comment by vauvenal5** [comment]
I consider this issue closed.

**Comment by igor-cali** [comment]
`v0.23.12` from F-Droid gives me this issue again (blank screen).

**Comment by vauvenal5** [comment]
Please re-open if it is still an issue.
